// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsgnmhyyeceqnnjbnidm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzZ25taHl5ZWNlcW5uamJuaWRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NjI3NTksImV4cCI6MjA1NjQzODc1OX0.n282r_sL8M9VpZ5EXtrBKuUqK_STM-2jo8I90v4vV78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);